### ISSUE TITLE
COM Interop failed to connect the Excel file

### ISSUE THREAD

**Issue by didierterrien** [sql-bi/AnalyzeInExcel#7]
Hello Marco,
Testing V1.1.1 I notice  Excel shows the dialog box  in order to approve opening the ODC file. I double checked I use version 1.1.1. I checked also the connection which is actually made with the ODC file.
I deleted the ODC file but it was created again by your tool so I'm sure COM Interop failed.
Please let me know if you need more information
Thanks in advance
Didier Terrien

**Comment by marcosqlbi** [comment]
Hi Didier, I'm really glad you wrote because there are cases where COM Interop fails and we don't understand why.
Please, can you tell me:
- what is the version of Excel you have
- what is the content of this Registry hive: HKEY_CLASSES_ROOT\Excel.Application\CLSID (see the image below, you probably have a different GUID or you don't have that registry key)
- what is the content of this Registry hive: HKEY_CLASSES_ROOT\Excel.Application\CurVer

I look forward to hearing from you!

![image](https://user-images.githubusercontent.com/13840816/90984392-e0e08900-e574-11ea-91d4-a5e13daea37f.png)

![image](https://user-images.githubusercontent.com/13840816/90984407-f9e93a00-e574-11ea-883e-9e7a31988c54.png)

**Comment by didierterrien** [comment]
Marco,

Here is the information:
- Office standard 2013
- CLSID = {00024500-0000-0000-C000-000000000046}
- CurVer = Excel.Application.15

Feel free to ask for more
Didier

**Comment by marcosqlbi** [comment]
Do you know whether you have (or you have had) other versions of Excel?
For example: in the registry you might have a hive HKEY_CLASSES_ROOT\Excel.Application.15 bot also HKEY_CLASSES_ROOT\Excel.Application.14 and HKEY_CLASSES_ROOT\Excel.Application.12 - please, can you tell me which hives do you have?

Other question: can you check whether you have this hive in the registry:
Computer\HKEY_CLASSES_ROOT\CLSID\{00024500-0000-0000-C000-000000000046}

If yes, can you provide the content of these registry keys:
Computer\HKEY_CLASSES_ROOT\CLSID\{00024500-0000-0000-C000-000000000046}\ProgID
Computer\HKEY_CLASSES_ROOT\CLSID\{00024500-0000-0000-C000-000000000046}\InprocServer32
Computer\HKEY_CLASSES_ROOT\CLSID\{00024500-0000-0000-C000-000000000046}\InprocHandler32
Computer\HKEY_CLASSES_ROOT\CLSID\{00024500-0000-0000-C000-000000000046}\VersionIndependentProgID

There seems to be a mismatch between the CLSID and the Excel version you have, but we need more details to understand what is going on. Technically, the tool finds that Excel.Application is available, but the COM Interop calls fails. The CLSID should be automatically identified by the Interop library, but on your machine it is not working. I would like to understand why because it's not the first time I see the issue reported by the telemetry, but it's the first time I have the ability to ask more details!

Thanks in advance!

**Comment by didierterrien** [comment]
Marco,
I have only HKEY_CLASSES_ROOT\Excel.Application.15
I have Computer\HKEY_CLASSES_ROOT\CLSID\\{00024500-0000-0000-C000-000000000046} ("\\" between CLSID and "{")

![image](https://user-images.githubusercontent.com/37301981/91032045-b4268300-e601-11ea-804f-09f8188515c0.png)

![image](https://user-images.githubusercontent.com/37301981/91032265-0071c300-e602-11ea-86e6-d31343a765dd.png)

Ask for more if needed

**Comment by marcosqlbi** [comment]
Can you do the same for this hive in the registry:
Computer\HKEY_CLASSES_ROOT\CLSID{000208D5-0000-0000-C000-000000000046}

If you have it, can you provide the content of these registry keys (the screenshots you made before are perfect):
Computer\HKEY_CLASSES_ROOT\CLSID{000208D5-0000-0000-C000-000000000046}\ProgID
Computer\HKEY_CLASSES_ROOT\CLSID{000208D5-0000-0000-C000-000000000046}\InprocServer32
Computer\HKEY_CLASSES_ROOT\CLSID{000208D5-0000-0000-C000-000000000046}\InprocHandler32
Computer\HKEY_CLASSES_ROOT\CLSID{000208D5-0000-0000-C000-000000000046}\VersionIndependentProgID

Thanks!

**Comment by didierterrien** [comment]
I don't have the one you mentioned. Here is what looks the same :

![image](https://user-images.githubusercontent.com/37301981/91036188-349bb280-e607-11ea-9dc1-5aac7a2b0f12.png)

**Comment by marcosqlbi** [comment]
Question: do you use DAX Studio?
If you create a Power Pivot model in Excel, does DAX Studio add-in works?
I would say that there is some issue in the Excel configuration and any COM Interop call is going to fail on your PC. However, I don't have evidence for that. It could also be some mismatch between 32-bit and 64-bit, even though I guess you have Excel 32-bit installed and this shouldn't be the case.

Another workaround is using an IDispatch based approach instead of the COM Interop one. We opted for COM Interop in v1.1, reverting to the ODC file if COM Interop fails. I think we could try this sequence:
COM Interop --> IDispatch --> ODC file

Let me know if you have other details we should take into account.
Thanks!

**Comment by didierterrien** [comment]
I do use DAX studio but not in Excel. I even don't have Power Pivot installed on my machine. DAX studio works very well in External tools.

If I launch Analyze in Excel from Power BI desktop and then click on DAX studio button in Excel, I get this error :
![image](https://user-images.githubusercontent.com/37301981/91045116-a7f8f080-e616-11ea-85e0-98396a0fc69b.png)

In Excel options, I noticed I have 2 DAX studio addins. One seems to be a debug version (may be coming from Visual Studio as I tried DAX studio source code from Github) :
![image](https://user-images.githubusercontent.com/37301981/91044699-04a7db80-e616-11ea-8634-c393104b1426.png)

Yes I use a 32bits version :
![image](https://user-images.githubusercontent.com/37301981/91045823-be537c00-e617-11ea-957a-0312c935ea0a.png)

I will be available to test other approaches. Happy to provide some help.

**Comment by marcosqlbi** [comment]
If you don't have Power Pivot installed in Excel, the AddIn in Excel is not that useful (you don't have a Power Pivot model, as you see in the screenshot).
I'm sure the two add-ins are there because you installed one from Visual Studio.

I don't need other tests at the moment, I will update you as soon as we have something new to test.
Thanks!

**Comment by marcosqlbi** [comment]
Didier, please can you try this version?
https://cdn.sqlbi.com/updates/AnalyzeInExcel-1.1.2.msi

Let me know if it works - it should open the Excel file without creating the ODC file or not.
It tries to use IDispatch of COM Interop fails.
I look forward to hearing from you!

**Comment by didierterrien** [comment]
Thank you Marco,

It worked :
![image](https://user-images.githubusercontent.com/37301981/91299179-824c2280-e7a1-11ea-9620-50e8f102ef04.png)

**Comment by marcosqlbi** [comment]
Great! Thanks for the prompt feedback, I'm going to publish this release soon because there are other people who had the same experience.
